FROM rust:1.44-slim AS build


RUN USER=root cargo new sudoku_generator 
WORKDIR /sudoku_generator 
COPY Cargo.toml Cargo.lock ./
RUN cargo build --release

COPY src ./src
RUN cargo build --bin generate --release 

FROM rust:1.44-slim 
COPY --from=build /sudoku_generator/target/release/generate /

ENTRYPOINT ["/generate"]
CMD ["diag", "50000"]
