apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
     <source>
         @type tail 
         path /var/log/1.log
         pos_file /var/log/1.log.pos
         tag sudoku.gen
         <parse>
             @type json 
         </parse>
     </source>

     <match sudoku.gen>
        @type http
        # update this with
        # melange-sudoku-db 
        endpoint http://melange:5984/sudoku
        http_method post
        content_type application/json
        retryable_response_codes [503, 404]

        # couchdb only likes json
        <format>
             @type json
        </format>

        # tag 'container_id' is needed so that each individual
        # output from the generator is posted as an individual
        # request.
        <buffer container_id>
            flush_interval 2s
            overflow_action block
        </buffer>

        # TODO: is there another way to get this so that its not
        # in this config file
        <auth>
            method basic
            username admin
            password Bardop0nd
        </auth>
     </match>
